Avoid -fno-common with GCC 10
Which breaks the build due to the twamp-dataplane-offload.patch

/usr/bin/ld: ../owamp/libowamp.a(endpoint.o):./owamp/../owamp/vyatta-endpoint.h:28: multiple definition of `dataplane_offload_ops'; twampd-vyatta-dataplane.o:./owampd/../owamp/vyatta-endpoint.h:28: first defined here

GCC 10 has -fno-common enabled by default:
https://gcc.gnu.org/gcc-10/porting_to.html

The usage of dataplane_offload_ops in libowamp and owampd needs to be
reworked.

VRVDR-56480